In [2]:
import numpy as np

## Solving Linear Systems

In [3]:

## Theorically the same but implemented differently
# x = np.linalg.inv(A).dot(b)
# x = np.linalg.solve(A, b) #prefered

A = np.array([[1, 1], [1.5, 4]])
b = np.array([2200, 5050])

In [4]:
np.linalg.solve(A, b)

array([1500.,  700.])

In [6]:
np.linalg.inv(A).dot(b)

array([1500.,  700.])

## Generating data, random distributions

In [8]:
## array of zeros
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
## array of ones
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
## random number
np.random.random()

0.4041052836537763

In [6]:
## random numbers from uniform dist
np.random.random((2, 3))

array([[0.91885837, 0.95596049, 0.12765838],
       [0.75733434, 0.34386033, 0.00751009]])

In [7]:
## random numbers from normal dist
np.random.randn(2, 3)

array([[ 1.44840414,  1.23617045,  0.00965691],
       [-0.50410314, -0.43485362, -1.61515777]])